version: '3.8'
services:
  db:
    container_name: drone_alfredo_ochoa
    image: postgres_drone
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: musala_drone
    ports:
      - "6543:5432"

